/*
Wether these tables are to be used has yet to be decided
 */

CREATE SEQUENCE ID_SEQ; 

CREATE TABLE USERS(
	ID INT NOT NULL,
	USERNAME VARCHAR2(32) NOT NULL,
	FULLNAME VARCHAR2(255) NOT NULL,
	PASSWORD VARCHAR2(255) NOT NULL,
	EMAIL VARCHAR2(64),
	MOBILE INT,
	CREATE_BY VARCHAR2(255),
	CREATE_DATE TIMESTAMP,
	UPDATE_BY VARCHAR2(255),
	UPDATE_DATE TIMESTAMP,
	DELETE_BY VARCHAR2(255),
	DELETE_DATE TIMESTAMP,
	IS_DISABLED CHAR(1) DEFAULT 'N',
	IS_TUTOR CHAR(1) DEFAULT 'N',
	IS_VERIFIED CHAR(1) DEFAULT 'N',
  PRIMARY KEY(ID)
);
	
COMMENT ON COLUMN "USERS"."ID" IS 'ID';
COMMENT ON COLUMN "USERS"."USERNAME" IS 'Users ID';
COMMENT ON COLUMN "USERS"."FULLNAME" IS 'Users Name';
COMMENT ON COLUMN "USERS"."PASSWORD" IS 'Password(Encrypted)';
COMMENT ON COLUMN "USERS"."EMAIL" IS 'Email';
COMMENT ON COLUMN "USERS"."MOBILE" IS 'Mobile No';
COMMENT ON COLUMN "USERS"."CREATE_BY" IS 'Created By';
COMMENT ON COLUMN "USERS"."CREATE_DATE" IS 'Date Created';
COMMENT ON COLUMN "USERS"."UPDATE_BY" IS 'Updated By';
COMMENT ON COLUMN "USERS"."UPDATE_DATE" IS 'Date Updated';
COMMENT ON COLUMN "USERS"."DELETE_BY" IS 'Deleted By';
COMMENT ON COLUMN "USERS"."DELETE_DATE" IS 'Date Deleted';
COMMENT ON COLUMN "USERS"."IS_DISABLED" IS 'Disabled';
COMMENT ON COLUMN "USERS"."IS_TUTOR" IS 'Tutor Status';
COMMENT ON COLUMN "USERS"."IS_VERIFIED" IS 'Verification Status';
COMMENT ON TABLE "USERS"  IS 'User';

CREATE TABLE SUBJECT_CATEGORY(
	ID INT NOT NULL,
	TITLE VARCHAR2(255) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE SUBJECT(
	ID INT NOT NULL,
	TITLE VARCHAR2(255),
	DESCRIPTION VARCHAR2(255),
	CATEGORY_ID INT references SUBJECT_CATEGORY(ID),
	PRIMARY KEY (ID)	
);

CREATE TABLE USER_SUBJECT(
	ID INT NOT NULL,
	USER_ID INT references USERS(ID),
	SUBJECT_ID INT references SUBJECT(ID),	
	PRIMARY KEY (ID)
);


url="jdbc:oracle:thin:@demo.gnomontech.com:1521:orcl"
url="jdbc:oracle:thin:@ubertutor.cxbqqbwmdfap.us-west-2.rds.amazonaws.com:1521:orcl"